<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260829210727 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create MVP 1 domain model tables for publications and vocabulary.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE publication (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, author VARCHAR(255) DEFAULT NULL, type VARCHAR(20) NOT NULL, language VARCHAR(8) NOT NULL, raw_text TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, analyzed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE publication_vocabulary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurrences INT NOT NULL, publication_id INT NOT NULL, vocabulary_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_publication_vocabulary_publication ON publication_vocabulary (publication_id)');
        $this->addSql('CREATE INDEX idx_publication_vocabulary_vocabulary_item ON publication_vocabulary (vocabulary_item_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_publication_vocabulary_identity ON publication_vocabulary (publication_id, vocabulary_item_id)');
        $this->addSql('CREATE TABLE vocabulary_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, language VARCHAR(8) NOT NULL, lemma VARCHAR(255) NOT NULL, part_of_speech VARCHAR(32) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_vocabulary_item_identity ON vocabulary_item (language, lemma, part_of_speech)');
        $this->addSql('CREATE TABLE vocabulary_occurrence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_form VARCHAR(255) NOT NULL, sentence TEXT DEFAULT NULL, position INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, publication_id INT NOT NULL, vocabulary_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_vocabulary_occurrence_publication ON vocabulary_occurrence (publication_id)');
        $this->addSql('CREATE INDEX idx_vocabulary_occurrence_vocabulary_item ON vocabulary_occurrence (vocabulary_item_id)');
        $this->addSql('ALTER TABLE publication_vocabulary ADD CONSTRAINT FK_FEEE8C9A38B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE publication_vocabulary ADD CONSTRAINT FK_FEEE8C9A25F78426 FOREIGN KEY (vocabulary_item_id) REFERENCES vocabulary_item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vocabulary_occurrence ADD CONSTRAINT FK_CDA9C1C338B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vocabulary_occurrence ADD CONSTRAINT FK_CDA9C1C325F78426 FOREIGN KEY (vocabulary_item_id) REFERENCES vocabulary_item (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE publication_vocabulary DROP CONSTRAINT FK_FEEE8C9A38B217A7');
        $this->addSql('ALTER TABLE publication_vocabulary DROP CONSTRAINT FK_FEEE8C9A25F78426');
        $this->addSql('ALTER TABLE vocabulary_occurrence DROP CONSTRAINT FK_CDA9C1C338B217A7');
        $this->addSql('ALTER TABLE vocabulary_occurrence DROP CONSTRAINT FK_CDA9C1C325F78426');
        $this->addSql('DROP TABLE publication');
        $this->addSql('DROP TABLE publication_vocabulary');
        $this->addSql('DROP TABLE vocabulary_item');
        $this->addSql('DROP TABLE vocabulary_occurrence');
    }
}
