<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260904070000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add context-specific publication vocabulary enrichment.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE publication_vocabulary_enrichment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, publication_vocabulary_id INT NOT NULL, translation_pl TEXT NOT NULL, definition_en TEXT NOT NULL, meaning_in_context TEXT NOT NULL, simple_example TEXT NOT NULL, cefr_level VARCHAR(2) DEFAULT NULL, source_sentence TEXT NOT NULL, provider VARCHAR(64) DEFAULT NULL, model VARCHAR(128) DEFAULT NULL, prompt_version VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_51AE84641E0D0 ON publication_vocabulary_enrichment (publication_vocabulary_id)');
        $this->addSql('ALTER TABLE publication_vocabulary_enrichment ADD CONSTRAINT FK_B1DB890677B72435 FOREIGN KEY (publication_vocabulary_id) REFERENCES publication_vocabulary (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE publication_vocabulary_enrichment DROP CONSTRAINT FK_B1DB890677B72435');
        $this->addSql('DROP TABLE publication_vocabulary_enrichment');
    }
}
