<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260923090000 extends AbstractMigration
{
    public function getDescription(): string { return 'Persist single-item asynchronous enrichment jobs and request revisions.'; }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE publication_vocabulary ADD enrichment_revision INT DEFAULT 0 NOT NULL');
        $this->addSql('CREATE TABLE publication_vocabulary_enrichment_job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, publication_vocabulary_id INT NOT NULL, request_revision INT NOT NULL, status VARCHAR(16) NOT NULL, stage VARCHAR(16) NOT NULL, active_llm_job_id VARCHAR(36) DEFAULT NULL, model VARCHAR(128) DEFAULT NULL, provider VARCHAR(64) DEFAULT NULL, prompt_version VARCHAR(64) DEFAULT NULL, request_snapshot JSON NOT NULL, candidate JSON DEFAULT NULL, failure VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ENRICHMENT_JOB_UUID ON publication_vocabulary_enrichment_job (active_llm_job_id)');
        $this->addSql('CREATE INDEX idx_enrichment_job_context ON publication_vocabulary_enrichment_job (publication_vocabulary_id, id)');
        $this->addSql('ALTER TABLE publication_vocabulary_enrichment_job ADD CONSTRAINT FK_ENRICHMENT_JOB_CONTEXT FOREIGN KEY (publication_vocabulary_id) REFERENCES publication_vocabulary (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE publication_vocabulary_enrichment_job');
        $this->addSql('ALTER TABLE publication_vocabulary DROP enrichment_revision');
    }
}
