<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260905090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add contextual learning cards.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE learning_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vocabulary_item_id INT NOT NULL, publication_vocabulary_id INT DEFAULT NULL, publication_vocabulary_enrichment_id INT DEFAULT NULL, type VARCHAR(32) NOT NULL, front TEXT NOT NULL, back TEXT NOT NULL, context_sentence TEXT DEFAULT NULL, cloze_sentence TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_learning_card_vocabulary_item ON learning_card (vocabulary_item_id)');
        $this->addSql('CREATE INDEX idx_learning_card_publication_vocabulary ON learning_card (publication_vocabulary_id)');
        $this->addSql('CREATE INDEX idx_learning_card_type ON learning_card (type)');
        $this->addSql('CREATE INDEX idx_learning_card_active ON learning_card (is_active)');
        $this->addSql('CREATE INDEX idx_learning_card_created_at ON learning_card (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_learning_card_publication_vocabulary_type ON learning_card (publication_vocabulary_id, type)');
        $this->addSql('CREATE INDEX IDX_5D70B629F0E11780 ON learning_card (publication_vocabulary_enrichment_id)');
        $this->addSql('ALTER TABLE learning_card ADD CONSTRAINT FK_5D70B62925F78426 FOREIGN KEY (vocabulary_item_id) REFERENCES vocabulary_item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE learning_card ADD CONSTRAINT FK_5D70B62977B72435 FOREIGN KEY (publication_vocabulary_id) REFERENCES publication_vocabulary (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE learning_card ADD CONSTRAINT FK_5D70B629F0E11780 FOREIGN KEY (publication_vocabulary_enrichment_id) REFERENCES publication_vocabulary_enrichment (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE learning_card DROP CONSTRAINT FK_5D70B62925F78426');
        $this->addSql('ALTER TABLE learning_card DROP CONSTRAINT FK_5D70B62977B72435');
        $this->addSql('ALTER TABLE learning_card DROP CONSTRAINT FK_5D70B629F0E11780');
        $this->addSql('DROP TABLE learning_card');
    }
}
