<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260905130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add immutable learning review history.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE learning_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, learning_card_id INT DEFAULT NULL, rating VARCHAR(16) NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, response_time_ms INT NOT NULL, study_session_id VARCHAR(36) NOT NULL, study_position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_learning_review_card ON learning_review (learning_card_id)');
        $this->addSql('CREATE INDEX idx_learning_review_reviewed_at ON learning_review (reviewed_at)');
        $this->addSql('CREATE INDEX idx_learning_review_rating ON learning_review (rating)');
        $this->addSql('CREATE INDEX idx_learning_review_session ON learning_review (study_session_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_learning_review_study_presentation ON learning_review (study_session_id, study_position)');
        $this->addSql('ALTER TABLE learning_review ADD CONSTRAINT FK_7BE296595D70B629 FOREIGN KEY (learning_card_id) REFERENCES learning_card (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE learning_review DROP CONSTRAINT FK_7BE296595D70B629');
        $this->addSql('DROP TABLE learning_review');
    }
}
